### PR TITLE
Process completion in insert mode

### LINKED ISSUE #18: Complete as you type
Is it possible to have autocompletion in insert mode on typing? Without calling shortcut for `rpcnotify(g:neovim_channel, 'Gui', 'triggerCommand', 'TextEditor.CompleteThis')` every time.

### PR DESCRIPTION
**Pull request by Shatur95**
Closes #18. I disable event filtering for events in insert mode that contains text to enable auto-completion. I used `startsWith` because this can be applied for `ic` mode.

### CODE REVIEW

**Comment by sassanh** [comment]
It's not working for me. Does it work on your system?

**Comment by Shatur95** [comment]
Yes. I even just now tested it without any plugins. The completion must suggest items after 3 characters. For example, open source code of this plugin, open any class member function and start typing "thi" in insert mode - you must see completion.

**Comment by sassanh** [comment]
This is how it looks here:

Screencast_04-06-2020_10_43_48 AM

**Comment by Shatur95** [comment]
@sassanh, that's weird, I do not have such behavior. But thank you, I will look into it.

**Comment by Shatur95** [comment]
I managed to reproduce the problem, I have it too, but in very rare cases.
Now everything should work. Could you check it again?

**Comment by Shatur95** [comment]
Okay, I will test QML.

**Comment by Shatur95** [comment]
Sorry, it was my mistake. Could you test it again?

**Comment by sassanh** [comment]
It's now working for QML as well but it breaks some of vim functionality, it breaks `imap` mappings, for example I have ``imap ` <c-c>`` and it's not working in this branch. So I think we should pass keys to neovim in any circumstances and instead trigger the auto-completion from neovim because neovim has better contextual information to conclude a keypress edits the buffer or not and if it edits the buffer what are the side effects.

**Comment by Shatur95** [comment]
You're right. I just didn’t think that someone might need to assign a letter key in insert mode. So, we need to check if buffer changed in Neovim in insert mode and if yes - send corresponding event to the Qt Creator?

**Comment by Shatur95** [comment]
I will reopen due to rebase in master.

**Pull request closed without merging**
