### PR TITLE
chore: unify QtCreator fetching code with CI

### PR DESCRIPTION
**Pull request by gikari**
Before this change, QtCreator fetching code from external directory was
different from the one from CI scripts. You'd have to specify QtCreator
version in two places, and the `external` fetch was more complex,
requiring you to change file names and checksums for every platform
once the version of QtCreator changes.

This change unifies the way to download QtCreator, while simplifying
it. Only one place to set Qt

Some drawbacks:
- Qt Creator now unpacks to `external` source directory, requiring you
to delete the `dist` dir, if you want a full clean build. In the most
cases, since the downloaded files are binaries, that are stable, you
would not want to do that often.
- Since Qt Packaging script is invoking CMake and comes from QtCreator
distribution, we have to download the QtCreator outside the CMake
build process, which makes things more complex. But we only need to
do this once, in the CI, so local builds are as simple, as they were.
- Windows MinGW version is deleted. Official downloads from Qt do not provide separate binaries for it. We use GCC on Linux (which is mostly the same essentially), so the benefits of using yet another compiler is not worth the effort.

## Test Plan

This was tested here: https://github.com/gikari/qnvim/actions/runs/3550716748

Local testing might be necessary:
- [x] Windows
- [x] Linux
- [x] macOS

### CODE REVIEW

**Comment by sassanh** [comment]
Thanks! Sorry for the late response, the diff is all good, the problem is I ran it once on macOS and it failed and I haven't find the time to check it again or investigate the issue, that's why it is taking long. I will check it again as soon as possible.

**Comment by gikari** [comment]
I've made some changes, so that you don't have to delete the `dist*` directory every time you wnat to change the downloaded Qt Creator version.

**Comment by sassanh** [comment]
OK, it is building on my machine, but it is downloading untracked files in root directory of the project:
```
On branch feature/unify-qtc-with-ci
Your branch is up to date with 'origin/feature/unify-qtc-with-ci'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        qtc_ver=4.15.2
        qtcreator.7z
        qtcreator_dev.7z

nothing added to commit but untracked files present (use "git add" to track)
```
Can we avoid this? Or add them to `.gitignore` maybe?

**Comment by gikari** [comment]
> OK, it is building on my machine, but it is downloading untracked files in root directory of the project:
> 
> ```
> On branch feature/unify-qtc-with-ci
> Your branch is up to date with 'origin/feature/unify-qtc-with-ci'.
> 
> Untracked files:
>   (use "git add <file>..." to include in what will be committed)
>         qtc_ver=4.15.2
>         qtcreator.7z
>         qtcreator_dev.7z
> 
> nothing added to commit but untracked files present (use "git add" to track)
> ```
> 
> Can we avoid this? Or add them to `.gitignore` maybe?

Hm, this should not happen. They supposed to be downloaded into build directory. I will look into it.

**Comment by gikari** [comment]
This might fix the problem. Just in case: `DownloadQtCreator.cmake` should not be imvoked manually on local machine. It is invoked by CMake automatically.

**Review by sassanh — APPROVED** [review]

**Comment by sassanh** [comment]
Thanks! It's all good now.

**Pull request merged**
