### PR TITLE
Setup CI for automatic plugin build and publishing

### PR DESCRIPTION
**Pull request by gikari**
## Summary

This change introduces GitHub CI workflow, that builds the plugin "on push" to any branch. When the tag is pushed to the repository, it creates a release with the archives for all systems (Windows, Linux and macOS), that can be downloaded and installed as a plugin into Qt Creator.

## Notes

- This changes the versioning of the plugin according to QtCreator releases. In general, it can be arbitrary, but due to incompatibly between versions of Qt Creator, I think it makes sense.
- The code, that fetches dependencies, is moved to `external` folder. Within it, there are some minor patches for neovim-qt, that  fixes some issues before they can be [merged](https://github.com/equalsraf/neovim-qt/pull/1030) upstream and released.
- The change is based on yml file modern QtCreator generates for the plugin projects with adjustments, like: pinning runners os tags, modernizing used GitHub actions and splitting the cmake code into files.

## Test Plan
This workflow was tested on my fork [here](https://github.com/gikari/qnvim/actions).

[This](https://github.com/gikari/qnvim/actions/runs/3504261406) is how it happens on push. [This](https://github.com/gikari/qnvim/actions/runs/3504169136) is how it happens on tag push.
The release would look like [the one here](https://github.com/gikari/qnvim/releases/tag/v4.15.2).

What to check:
- [x] The plugins from the artifacts are installable on Qt Creator 4.15.2 on all systems.

### CODE REVIEW

**Review by sassanh — APPROVED** [review]

**Comment by sassanh** [comment]
This is great! I just noticed a minor issue after approving the diff and trying to actually test it on my machine: in macOS version, the 7z file is not the plugin library itself, it is an incomplete "Qt Creator.app" macOS application which only contains the directory structure of the plugin and the plugin in that directory structure. It may be confusing for some users, it would be nice if we only provide the plugin file `libQNVim.dylib` instead of this directory structure so that users can easily install it in their "about plugins" dialog of Qt Creator.

**Comment by gikari** [comment]
To install the plugin, you need to give Qt Creator the archive from releases section in "About Plugins > Install Plugin..." dialog. At least this approach works on Windows. I am not sure about macOS, because the directories structure is different in the respective archive. Do I understand correctly, that the macOS archive does not work that way on your system?

**Comment by sassanh** [comment]
Yes, installing the archive works, so it's good to be merged.

**Comment by gikari** [comment]
I've made a small change, that removes RUNNER_OS variable, because CMake has a built-in alternative. Everything should be fine, since the release CI built and uploaded all artifacts correctly: https://github.com/gikari/qnvim/releases/tag/v4.15.2

**Review by sassanh — APPROVED** [review]
Thanks! looks good

**Pull request merged**
