### PR TITLE
Qt6 and Qt Creator 6.0.2 support

### PR DESCRIPTION
**Pull request by gikari**
This PR has two parts:
1. Using a [forked neovim-qt](https://github.com/gikari/neovim-qt) that has all the patches to support Qt6. It has a plenty, so merging them upstream will take some time. I will try to do that, if possible.
2. Updating the block selection code, so that it works with new Multiple Cursors API. It generally works, but there is a bug: when you press l in the selection mode at the end of the shortest line of block selection, your selection kind of breaks. Ideally, it should not be allowed to move the cursor further, but I don't know how to do that yet. Also, random multiple cursors might not work, because Neovim does not support multiple cursors currently, and I have no idea how should I sync that behavior to Neovim.

## Test Plan

1. Build the plugin and check, that block selection works with Qt Creator 6.

### CODE REVIEW

**Review by sassanh — CHANGES_REQUESTED** [review]

**Comment by sassanh** [comment]
> Using a [forked neovim-qt](https://github.com/gikari/neovim-qt) that has all the patches to support Qt6. It has a plenty, so merging them upstream will take some time. I will try to do that, if possible.

Would it be helpful to merge this to a new branch like `qtc-6` until your changes in neovim-qt are merged? We can mention it in README.md and run GitHub Actions on it too.

> Updating the block selection code, so that it works with new Multiple Cursors API. It generally works, but there is a bug: when you press l in the selection mode at the end of the shortest line of block selection, your selection kind of breaks. Ideally, it should not be allowed to move the cursor further, but I don't know how to do that yet. Also, random multiple cursors might not work, because Neovim does not support multiple cursors currently, and I have no idea how should I sync that behavior to Neovim.

Thanks for updating it! We can immediately merge it to `qtc-6` even with some expected bugs, but to merge it to the main branch I’d say let’s wait for a fix for this issue.

**Comment by sassanh** [comment]
2 observations:
1. When I build the plugin myself, install it and restart Qt Creator, I see this error in terminal:
```
Found invalid metadata in lib .../Library/Application Support/QtProject/Qt Creator/plugins/6.0.2/libQNVim.dylib: Invalid metadata version
```
but when I download it from [here](https://github.com/sassanh/qnvim/actions/runs/3666343139) it works.
2. When I press `v` and select some text, it will become extremely slow and unresponsive, and "syncFromVim" gets called continuously even when no key is pressed. As soon as I exit visual mode, it will become fast and responsive again. If it is not happening for you I can check if any vim plugin on my side is causing this behavior.

**Comment by gikari** [comment]
> 2 observations:
> 1. When I build the plugin myself, install it and restart Qt Creator, I see this error in terminal:
> ```
> Found invalid metadata in lib .../Library/Application Support/QtProject/Qt Creator/plugins/6.0.2/libQNVim.dylib: Invalid metadata version
> ```
> but when I download it from [here](https://github.com/sassanh/qnvim/actions/runs/3666343139) it works.

This happened to me, when I compiled plugin with Qt 6.4, but Qt 6.2 fixes this. This is probably because Qt Creator 6 was compiled with the version, that was the latest at the moment of it's release, which is probably 6.2, but I am not sure.


> 2. When I press `v` and select some text, it will become extremely slow and unresponsive, and "syncFromVim" gets called continuously even when no key is pressed. As soon as I exit visual mode, it will become fast and responsive again. If it is not happening for you I can check if any vim plugin on my side is causing this behavior.

I see this as well, but I am not sure how my changes could introduce that. Does master branch produces this as well?

**Comment by sassanh** [comment]
Very nice to see qtnvim working with Qt 6 and Qt Creator 6, I ran it on my machine and everything looked very good except visual mode as you mentioned. So I say let's merge it to `qtc-6` as you changed the target branch and then work on fixing visual mode. Let me know if you are blocked by something, I will probably have some time to work on it in February.

**Review by sassanh — APPROVED** [review]
Also you may want to activate GitHub actions for this new branch?

**Comment by gikari** [comment]
> Also you may want to activate GitHub actions for this new branch?

Yeah, I will do this in the next PR.

**Pull request merged**
